"""update

Revision ID: 01f93f4b9988
Revises: 16525dfee3f9
Create Date: 2022-04-13 21:00:33.685775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f93f4b9988'
down_revision = '16525dfee3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autoconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scrapingconfs', sa.String(), nullable=True, comment='以;间隔'))
        batch_op.add_column(sa.Column('transferconfs', sa.String(), nullable=True, comment='以;间隔'))
        batch_op.add_column(sa.Column('remark', sa.String(), nullable=True))
        batch_op.drop_column('mark')

    with op.batch_alter_table('transferconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.String(), nullable=True))
        batch_op.drop_column('mark')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mark', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('remark')

    with op.batch_alter_table('autoconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mark', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('remark')
        batch_op.drop_column('transferconfs')
        batch_op.drop_column('scrapingconfs')

    # ### end Alembic commands ###
