"""Update transferConfig

Revision ID: 13c0a3a534a0
Revises: a9c9e7063598
Create Date: 2021-09-18 14:15:01.405004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c0a3a534a0'
down_revision = 'a9c9e7063598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clean_others', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('replace_CJK', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferconfigs', schema=None) as batch_op:
        batch_op.drop_column('replace_CJK')
        batch_op.drop_column('clean_others')

    # ### end Alembic commands ###
