"""update scraping config

Revision ID: 16525dfee3f9
Revises: 39aa630232f1
Create Date: 2022-04-13 19:33:19.450917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16525dfee3f9'
down_revision = '39aa630232f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('remark')

    # ### end Alembic commands ###
