"""add deadtime

Revision ID: 17b29e2630f4
Revises: a76b476b9525
Create Date: 2022-06-15 17:15:15.952589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b29e2630f4'
down_revision = 'a76b476b9525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapingrecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadtime', sa.DateTime(), nullable=True, comment='time to delete files'))

    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadtime', sa.DateTime(), nullable=True, comment='time to delete files'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.drop_column('deadtime')

    with op.batch_alter_table('scrapingrecords', schema=None) as batch_op:
        batch_op.drop_column('deadtime')

    # ### end Alembic commands ###
