"""Add task number

Revision ID: 1eac15402cf5
Revises: de30b0f0cf2e
Create Date: 2021-06-24 10:03:02.291131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eac15402cf5'
down_revision = 'de30b0f0cf2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('finished', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'finished')
    op.drop_column('task', 'total')
    # ### end Alembic commands ###
