"""Add link type

Revision ID: 206e24daedc4
Revises: 1eac15402cf5
Create Date: 2021-07-15 10:07:21.342292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206e24daedc4'
down_revision = '1eac15402cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('link_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'link_type')
    # ### end Alembic commands ###
