"""add fix series tag

Revision ID: 25cc4c9d1c33
Revises: 13c0a3a534a0
Create Date: 2021-10-18 13:40:21.622995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cc4c9d1c33'
down_revision = '13c0a3a534a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fix_series', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferconfigs', schema=None) as batch_op:
        batch_op.drop_column('fix_series')

    # ### end Alembic commands ###
