"""Add extrafanart

Revision ID: 43e878537ab5
Revises: 206e24daedc4
Create Date: 2021-07-28 12:33:52.154813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e878537ab5'
down_revision = '206e24daedc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('extrafanart_enable', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('extrafanart_folder', sa.String(), server_default='extrafanart', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'extrafanart_folder')
    op.drop_column('settings', 'extrafanart_enable')
    # ### end Alembic commands ###
