"""update records

Revision ID: 484e6db26cb9
Revises: 5c6e23a62577
Create Date: 2024-03-02 14:00:44.337457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484e6db26cb9'
down_revision = '5c6e23a62577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapingconfigs', schema=None) as batch_op:
        batch_op.drop_column('proxy_timeout')
        batch_op.drop_column('proxy_retry')
        batch_op.drop_column('async_request')
        batch_op.drop_column('proxy_address')
        batch_op.drop_column('multi_scraping')
        batch_op.drop_column('proxy_type')
        batch_op.drop_column('proxy_enable')

    with op.batch_alter_table('scrapingrecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignored', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignored', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('locked')
        batch_op.drop_column('ignored')

    with op.batch_alter_table('scrapingrecords', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('locked')
        batch_op.drop_column('ignored')

    with op.batch_alter_table('scrapingconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proxy_enable', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('proxy_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('multi_scraping', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('proxy_address', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('async_request', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('proxy_retry', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('proxy_timeout', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
