"""add loglvl

Revision ID: 55d303fd558e
Revises: 98894b006faa
Create Date: 2022-06-22 22:38:25.023254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d303fd558e'
down_revision = '98894b006faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('localconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loglevel', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('localconfigs', schema=None) as batch_op:
        batch_op.drop_column('loglevel')

    # ### end Alembic commands ###
