"""add specifiedurl

Revision ID: 5c6e23a62577
Revises: 55d303fd558e
Create Date: 2022-07-29 15:30:08.183426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6e23a62577'
down_revision = '55d303fd558e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapingrecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specifiedsource', sa.String(), nullable=True, comment='specified scraping site'))
        batch_op.add_column(sa.Column('specifiedurl', sa.String(), nullable=True, comment='specified scraping site url'))
        batch_op.drop_column('scrapingurl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapingrecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scrapingurl', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('specifiedurl')
        batch_op.drop_column('specifiedsource')

    # ### end Alembic commands ###
