"""update series record

Revision ID: 67cbdd6413c3
Revises: 25cc4c9d1c33
Create Date: 2021-10-18 14:09:48.947312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cbdd6413c3'
down_revision = '25cc4c9d1c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('topfolder', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secondfolder', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('isepisode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('season', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('episode', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.drop_column('episode')
        batch_op.drop_column('season')
        batch_op.drop_column('isepisode')
        batch_op.drop_column('secondfolder')
        batch_op.drop_column('topfolder')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
