"""update records

Revision ID: 76a849adb003
Revises: 484e6db26cb9
Create Date: 2024-03-02 17:19:19.745250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a849adb003'
down_revision = '484e6db26cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapingrecords', schema=None) as batch_op:
        batch_op.alter_column('ignored',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)

    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.alter_column('ignored',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.alter_column('ignored',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('scrapingrecords', schema=None) as batch_op:
        batch_op.alter_column('ignored',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
