"""update scraping tags

Revision ID: 825048469450
Revises: e76363a21cbe
Create Date: 2022-02-22 16:53:40.433388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825048469450'
down_revision = 'e76363a21cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapingrecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leaktag', sa.Boolean(), nullable=True, comment='leak tag'))
        batch_op.add_column(sa.Column('uncensoredtag', sa.Boolean(), nullable=True, comment='uncensored tag'))
        batch_op.add_column(sa.Column('hacktag', sa.Boolean(), nullable=True, comment='hack tag'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapingrecords', schema=None) as batch_op:
        batch_op.drop_column('hacktag')
        batch_op.drop_column('uncensoredtag')
        batch_op.drop_column('leaktag')

    # ### end Alembic commands ###
