"""add transmission

Revision ID: 98894b006faa
Revises: ab98111cb095
Create Date: 2022-06-22 17:15:52.459637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98894b006faa'
down_revision = 'ab98111cb095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('localconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tr_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tr_username', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tr_passwd', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tr_prefix', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('localconfigs', schema=None) as batch_op:
        batch_op.drop_column('tr_prefix')
        batch_op.drop_column('tr_passwd')
        batch_op.drop_column('tr_username')
        batch_op.drop_column('tr_url')

    # ### end Alembic commands ###
