"""add auto watch

Revision ID: 98e01c6ecbdc
Revises: b7f1f83c525e
Create Date: 2024-05-09 22:52:16.179646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e01c6ecbdc'
down_revision = 'b7f1f83c525e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapingconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_watch', sa.Boolean(), nullable=True))

    with op.batch_alter_table('transferconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_watch', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferconfigs', schema=None) as batch_op:
        batch_op.drop_column('auto_watch')

    with op.batch_alter_table('scrapingconfigs', schema=None) as batch_op:
        batch_op.drop_column('auto_watch')

    # ### end Alembic commands ###
