"""rename table

Revision ID: 9b27f48ac200
Revises: 01f93f4b9988
Create Date: 2022-04-15 10:22:54.470754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b27f48ac200'
down_revision = '01f93f4b9988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('scrapingconfigs')
    except:
        pass
    try:
        op.rename_table('settings', 'scrapingconfigs')
    except:
        op.create_table('scrapingconfigs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('scrapingconfigs', 'settings')
    # ### end Alembic commands ###
