"""update morestoryline

Revision ID: a76b476b9525
Revises: f43a0835f0b5
Create Date: 2022-06-07 10:33:06.982589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = 'a76b476b9525'
down_revision = 'f43a0835f0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapingconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('morestoryline', sa.Boolean(), server_default=expression.true(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapingconfigs', schema=None) as batch_op:
        batch_op.drop_column('morestoryline')

    # ### end Alembic commands ###
