"""rename config table

Revision ID: ab98111cb095
Revises: 17b29e2630f4
Create Date: 2022-06-16 14:44:49.375653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression


# revision identifiers, used by Alembic.
revision = 'ab98111cb095'
down_revision = '17b29e2630f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('notificationconfigs')
    try:
        op.drop_table('localconfigs')
    except:
        pass
    try:
        op.rename_table('notificationconfigs', 'localconfigs')
        with op.batch_alter_table('localconfigs', schema=None) as batch_op:
            batch_op.add_column(sa.Column('task_clean', sa.Boolean(), server_default=expression.false(), nullable=True))
    except:
        op.create_table('localconfigs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('localconfigs', 'notificationconfigs')
    # ### end Alembic commands ###
