"""movie forced name

Revision ID: b7f1f83c525e
Revises: 76a849adb003
Create Date: 2024-03-02 20:50:41.966667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f1f83c525e'
down_revision = '76a849adb003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forcedname', sa.String(), nullable=True, comment='forced name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.drop_column('forcedname')

    # ### end Alembic commands ###
