"""Update config

Revision ID: c6d3cfb805e7
Revises: f6ca967bad99
Create Date: 2021-08-12 17:04:20.425316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d3cfb805e7'
down_revision = 'f6ca967bad99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('multi_scraping', sa.Boolean(), nullable=True, comment='Multiple file scraping at the same time'))
    op.add_column('settings', sa.Column('async_request', sa.Boolean(), nullable=True, comment='Scrape a movie asynchronously'))
    op.add_column('settings', sa.Column('cookies_javlib', sa.String(), nullable=True))
    op.drop_column('settings', 'soft_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('soft_link', sa.BOOLEAN(), nullable=True))
    op.drop_column('settings', 'cookies_javlib')
    op.drop_column('settings', 'async_request')
    op.drop_column('settings', 'multi_scraping')
    # ### end Alembic commands ###
