"""add minisize

Revision ID: d029a987b48c
Revises: 825048469450
Create Date: 2022-04-11 11:49:53.822184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd029a987b48c'
down_revision = '825048469450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escape_size', sa.Integer(), nullable=True))

    with op.batch_alter_table('transferconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escape_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferconfigs', schema=None) as batch_op:
        batch_op.drop_column('escape_size')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('escape_size')

    # ### end Alembic commands ###
