"""Add cookies

Revision ID: de30b0f0cf2e
Revises: 
Create Date: 2021-05-31 16:49:00.204118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de30b0f0cf2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('cookies_javdb', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'cookies_javdb')
    # ### end Alembic commands ###
