"""update proxy

Revision ID: f43a0835f0b5
Revises: 9b27f48ac200
Create Date: 2022-05-31 17:43:48.924481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43a0835f0b5'
down_revision = '9b27f48ac200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificationconfigs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proxy_enable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('proxy_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('proxy_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificationconfigs', schema=None) as batch_op:
        batch_op.drop_column('proxy_address')
        batch_op.drop_column('proxy_type')
        batch_op.drop_column('proxy_enable')
    # ### end Alembic commands ###
