"""Add scraping cd num 

Revision ID: f6ca967bad99
Revises: 43e878537ab5
Create Date: 2021-08-07 01:17:29.852648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ca967bad99'
down_revision = '43e878537ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrapingrecords', sa.Column('cdnum', sa.Integer(), nullable=True, comment='cd num'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrapingrecords', 'cdnum')
    # ### end Alembic commands ###
