#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" tomoki
usermod -o -u "$PUID" tomoki

echo "
-------------------------------------
.__ __                               
|__|  | _______ _______  ____  ______
|  |  |/ /\__  \\_  __ \/  _ \/  ___/
|  |    <  / __ \|  | \(  <_> )___ \ 
|__|__|_ \(____  /__|   \____/____  >
        \/     \/                 \/ 
-------------------------------------
Starting with
User uid:    $(id -u tomoki)
User gid:    $(id -g tomoki)
-------------------------------------
"

chown tomoki:tomoki /config
chown tomoki:tomoki /app

chown -R tomoki /app/data
chmod -R u+rwx /app/data
